Repository pytroll/pytroll-schedule, pull requests merged in 2024-11, with the labels that each got.

#70 Issue 69 add slstr
  trollsched/boundary.py
  trollsched/tests/test_satpass.py
Labels: enhancement

#92 Bugfix - slstr not yet properly supported
  trollsched/boundary.py
  trollsched/tests/test_satpass.py
Labels: bug, PCW

#81 Fix ftp downloading for older python versions
  trollsched/satpass.py
Labels: bug

#89 Issue 88 command line option avoid as list
  trollsched/schedule.py
  trollsched/tests/test_schedule.py
Labels: enhancement
